### ISSUE TITLE
Simple messages classified as errors during `record_test` startup

### ISSUE THREAD

**Issue by rpodcast** [rstudio/shinytest2#111]
I'm finally getting a chance to play with `shinytest2`! Running `shinytest2::record_test()` performs well, but I noticed that a few messages at startup that are nothing more than diagnostics are prefixed with `{shiny} R error -------`. Likely just a printing issue. This was executed on RStudio Workbench `1.4.1717-3` with  R 4.1.2 and `shinytest2` [8d61bb478c](https://github.com/rstudio/shinytest2/tree/8d61bb478c6c4e03ac13921adfa2f8ce9c67bf1b ).

```
> shinytest2::record_test("myapp")
Loading required package: shiny

Listening on http://127.0.0.1:5829
{shiny} R error ----------- Loading required package: shiny
{shiny} R error ----------- Running application in test mode.
{shiny} R error ----------- 
{shiny} R error ----------- Listening on http://127.0.0.1:20124
Saving test runner: tests/testthat.R
Saving test file: tests/testthat/test-shinytest2.R
Running recorded test: 
✓ | F W S  OK | Context
✓ |   5     3 | shinytest2 [5.7s]                                                                             
──────────────────────────────────────────────────────────────────────────────────────────────────────────────
Warning (test-shinytest2.R:7:3): {shinytest2} recording: myapp-test
Adding new file snapshot: 'tests/testhat/_snaps/myapp-test-001.png'

Warning (test-shinytest2.R:8:3): {shinytest2} recording: myapp-test
Adding new file snapshot: 'tests/testhat/_snaps/myapp-test-002_.png'

Warning (test-shinytest2.R:8:3): {shinytest2} recording: myapp-test
Adding new file snapshot: 'tests/testhat/_snaps/myapp-test-002.json'

Warning (test-shinytest2.R:9:3): {shinytest2} recording: myapp-test
Adding new file snapshot: 'tests/testhat/_snaps/myapp-test-003_.png'

Warning (test-shinytest2.R:9:3): {shinytest2} recording: myapp-test
Adding new file snapshot: 'tests/testhat/_snaps/myapp-test-003.json'
──────────────────────────────────────────────────────────────────────────────────────────────────────────────

══ Results ═══════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 5.7 s

[ FAIL 0 | WARN 5 | SKIP 0 | PASS 3 ]
```

**Comment by schloerke** [comment]
`message()` prints to `stderr`, not `stdout`. So `callr` captures the `message()` calls to `stderr`.

This is expected behavior, but will keep it open until docs have addressed it.

**Comment by schloerke** [comment]
If `cat()` or `print()` is used, then `stdout` will capture the text.

**Comment by daattali** [comment]
@schloerke do the docs address this now? I just tried out shinytest2 for the first time and I was also noticing the same strange messages. I couldn't see anything about it in the docs but I might have not looked hard enough

**Comment by schloerke** [comment]
@daattali I have it under https://rstudio.github.io/shinytest2/reference/AppDriver.html#returns-14 via https://github.com/rstudio/shinytest2/blob/03ec73408c5cb623232aee1dbdb3a7686fad030b/R/app-driver.R#L1404-L1415 .

But it feels like it should have more exposure..

Should we add it to the FAQ? Where did you look first?
