### ISSUE TITLE
Display text diff of failing JSON files

### ISSUE THREAD

**Issue by schloerke** [rstudio/shinytest2#146]
Similar to https://github.com/r-lib/vdiffr/blob/fc03e91cccac04baa875063513b630d80c02e197/R/expect-doppelganger.R#L127-L151

Printing like https://github.com/r-lib/vdiffr/blob/fc03e91cccac04baa875063513b630d80c02e197/R/utils.R#L34-L39 and https://github.com/r-lib/vdiffr/blob/fc03e91cccac04baa875063513b630d80c02e197/R/utils.R#L49-L69

**Comment by alex-silverman** [comment]
I'm not clear how/when the diff is shown. When I run the GHA and the tests fail due to differences in the JSON snapshot files, there is no difference viewed:

![image](https://github.com/rstudio/shinytest2/assets/3285721/aa1aa258-e1e0-4323-85e8-538de72f641a)

I'm using shinytest2 0.3.1.
