### ISSUE TITLE
`expect_download` fails with binary (xlsx, zip, ...) files

### ISSUE THREAD

**Issue by bersbersbers** [rstudio/shinytest2#159]
Again, no reprex, but a stacktrace and code analysis. This happens when downloading an XLSX (technically a ZIP) file:

```
Error (test-xyz.R:24:5): xyz
Error in `brio::read_lines(old)`: embedded nul in string: 'PK\003\004\024\0\b\b\b\0\0\0!R\0\0\0...
Backtrace:
  1. get_tab_shapshots(...)
       at test-combo_sample-sep_xra_step.R:24:4
  2. app$expect_download(cran = TRUE, button, name = filename)
  3. shinytest2:::app_expect_download(...)
       at shinytest2/R/app-driver.R:621:6
  4. shinytest2:::app__expect_snapshot_file(...)
       at shinytest2/R/app-driver-expect-download.R:63:2
  6. testthat::expect_snapshot_file(...)
       at shinytest2/R/expect-snapshot.R:35:2
  7. snapshotter$take_file_snapshot(...)
       at testthat/R/snapshot-file.R:129:2
  8. testthat:::snapshot_file_equal(...)
       at testthat/R/snapshot-reporter.R:101:6
  9. testthat file_equal(cur_path, path)
       at testthat/R/snapshot-file.R:178:4
 10. brio::read_lines(old)
       at testthat/R/snapshot-file.R:259:2
```

I think the problem is here, in line 67:

https://github.com/rstudio/shinytest2/blob/6f195b1c66c13317f3cba758b6e0d5ffdfae80b8/R/app-driver-expect-download.R#L63-L68

Which leads to the wrong reader being selected here:

https://github.com/r-lib/testthat/blob/22a68dd85b65c95173424760a78955b6c55f3848/R/snapshot-file.R#L248-L262

This probably went unnoticed because https://github.com/rstudio/shinytest2/blob/main/tests/testthat/apps/download/app.R only has csv files for download tests.

**Comment by bersbersbers** [comment]
I think it would be good to expose `compare` as an argument to `app_expect_download`, like this:

```
app_expect_download <- function(
  self,
  private,
  output,
  ...,
  compare = testthat::compare_file_text, # this is new
  name = NULL,
  cran = FALSE
) {
```

and then call
```
  app__expect_snapshot_file(
    self, private,
    snapshot_info$download_path,
    cran = cran,
    compare = compare
  )
```
below.

This would also allow users to apply some postprocessing between downloading and comparing the file, which is easily possible in `shinytest` but not (currently) in `shinytest2`.

**Comment by schloerke** [comment]
I like the `compare` arg idea 😄
