### ISSUE TITLE
Should AppDriver call `$stop()` on test exit by default?

### ISSUE THREAD

**Issue by schloerke** [rstudio/shinytest2#162]
I'm not necessarily running out of ports, but it would be helpful to have the AppDriver object clean up when its done.

Should we add an argument to call `$stop()` when the calling environment exits? I'd imagine this should only be done in testing context (`testthat::is_testing()`). Maybe `AppDriver$new(defer_stop = TRUE)` or `AppDriver$new(stop_on_exit = TRUE)`

My worry is that users will make a helper function that will return an `AppDriver`, but then the newly created `AppDriver` object will shut down right away.

-------------------

cc @DivadNojnarg Thoughts? I see you perform manual calls to `$stop()` for every test block.  This makes it seem like boilerplate.

**Comment by DivadNojnarg** [comment]
I don't think creating a specific parameter is necessary. This is something end-users can do in 1 line. As you said, it could cause more issues. Instead, maybe add a note in the documentation: be careful to clean unused drivers 🧹

**Comment by schloerke** [comment]
On garbage collection, everything is shut down. Maybe I'll add a note in the FAQ

- [ ] Add note in FAQ about shutting down when done
