### ISSUE TITLE
{usethis} should move to Imports rather than Suggests?

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest2#193]
I just tried installing {shinytest2} in a brand new environment. Running `shinytest2::record_test()` was working fine all the way until the end when I clicked the "Save test and exit" button. Clicking that button resulted in an error in the console:

```
Error in write_union("tests/testthat/setup.R", comments = "# Load application support files into testing environment",  : 
  The package `usethis` is required.
```

To me this suggests that {usethis} is an essential package and should be automatically installed when {shinytest2} is installed. Since `record_test()` is the recommended way of using this package, that function should work out of the box. 

Feel free to close this issue if you disagree :)

**Comment by schloerke** [comment]
Yes! I agree.

The logic had changed since adding usethis

**Comment by schloerke** [comment]
Going to adjust internal logic to not require usethis for recordings. 

-> Going to keep usethis as Suggests.

**Comment by daattali** [comment]
I don't want to open a new issue, so I'll mention here:
Some other functions mentioned in the Getting Started page also don't work without installing packages. I remember trying to blindly follow the docs and getting scared when things weren't working and I was getting errors. I believe it was vdiffr and showimage. Perhaps when saying to look at the differences using snapshot_review(), adding a short phrase like "(you'll need to have the X package installed)" will be good

**Comment by schloerke** [comment]
( Moved to new issue https://github.com/rstudio/shinytest2/issues/198 )
