### ISSUE TITLE
[Documentation] Images aren't showing on the pkgdown website

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest2#195]
I'm currently reading the Getting Started page https://rstudio.github.io/shinytest2/articles/shinytest2.html and it looks like there should be some images there but none are showing. It creates an awkward flow because the wording makes me want to see an image, see scrfeenshot below for two examples

![image](https://user-images.githubusercontent.com/952340/166345070-aec20f8b-47f3-418c-8a81-4771a3bad35e.png)

**Comment by schloerke** [comment]
Thank you!
