### ISSUE TITLE
Start the test at the middle of the application

### ISSUE THREAD

**Issue by shahronak47** [rstudio/shinytest2#212]
We have a very complicated shiny application. It has a login screen, then user needs to select some value from the dropdown, a report is generated along with table and many other steps. I want to test out a very specific portion of the app. Using `shinytest2` the tests starts recording from the beginning and records each and every step in the process. Can we have control over what gets recorded? If yes, then I can skip all the background steps which are not relevant and  focus only on the part that we want to test. Maybe we can have a start recording and stop recording button. 

If this can be done it will also solve https://github.com/rstudio/shinytest2/issues/211 as we can skip recording for the login screen and it will not save passwords in the test file.

**Comment by schloerke** [comment]
You are free to adjust your recording made by `record_app()`. I even recommend that you trim the code that was recorded to only submit inputs that are necessary.

`{shinytest2}`'s role is to replay interactions with your app and make expectations at different time points.

If a typical user needs to use the login screen, then `{shinytest2}` test code will need to log in as well.  Similar to #211, you can change the UI / Server logic given the value of `getOption("shiny.testmode", FALSE)` to make testing easier... but knowing it is not exactly how the user will interact with the app.

**Comment by schloerke** [comment]
Closing as request is not possible
