### ISSUE TITLE
Package option for `wait_for_*()` timeouts

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/shinytest2#213]
If you're using a lot of `$wait_for_js()` calls, 30 seconds is a massively long timeout, and it'd be nice to be able to set a global option for the default timeout, e.g.

```r
options(shinytest2.wait_for_js.timeout = 5 * 1000)
```

instead of having to include `timeout = 5 * 1000` in all of my calls to `$wait_for_js()`. I would imagine heavy users of other `wait_for_*()` functions would benefit from similar options.

An alternative would be to lower the timeout for all of the wait functions to something reasonably small, e.g. 5 or 10 seconds, and then users who know they need to wait longer can opt into a longer wait time. (And I guess you'd also use longer timeouts for app startup.)

**Comment by schloerke** [comment]
Would it be fair if all timeouts (other than to `$new()`) be lowered to 3 seconds? 

Current timeout values:
* `$new(load_timeout = 10 * 1000)` (locally); `$new(load_timeout = 20 * 1000)` (CI)
* `$set_inputs(timeout_= 3 * 1000)` (same timeout for`$click(input=)`)
* `$upload_file(timeout_ = 3 * 1000)`
* `$expect_js(timeout = 15 * 1000)`
* `$get_js(timeout = 15 * 1000)`
* `$run_js(timeout = 15 * 1000)`
* `$wait_for_idle(timeout = 30 * 1000)`
* `$wait_for_value(timeout = 15 * 1000)`
* `$wait_for_js(timeout = 30 * 1000)`

------------------------------

And/Or should we adopt a bunch of option for the default values?

* `timeout` - many methods above
* `duration` - `$wait_for_idle()`
* `interval` - `$wait_for_value()`, `$wait_for_js()`
* `height`/`width` - Init window size
* `variant` - Init variant
* `expect_values_screenshot_args` - Init value

**Comment by gadenbuie** [comment]
3 or 4 seconds for all but the `$new()` method seems reasonable to me, as does making this setting controllable by a single default value. Cypress uses [4 seconds and a global timeout option](https://docs.cypress.io/guides/core-concepts/retry-ability#Timeouts).

**Comment by schloerke** [comment]
I believe there is legacy standard of 3 seconds with `{shinytest}`. So I'm ok with keeping it at 3 seconds.

What about a single value with individual overrides? Similar to ggplot2 x axis text inherits from ggplot2 text, we could have `shinytest2.timeout` default to `3 * 1000` (the global default) and`shinytest2.get_js.timeout` would use `shinytest2.timeout` if `shinytest2.get_js.timeout` is not set.

Or should we just do a single global option and can use args otherwise?

**Comment by gadenbuie** [comment]
I think I would be most likely to either

1. Know there's a particular spot where I need longer timeouts where I adjust the argument directly
2. Or just globally increase the timeouts because everything is slow.

So I'm in favor of a single default. Also `withr::local_options()` or `withr::with_options()` would be a great way to scope increased timeouts to a particular test or part of a test.

**Comment by schloerke** [comment]
Also need a `shinytest2.threshold` value for #231

**Comment by wch** [comment]
Another possibility:

```R
app$initalize(timeout = st2_timeout(steps = 10))

app$getjs(timeout = st2_timeout())


st2_timeout <- function(steps = 1) {
  time <- factor * getOption("shinytest.timeout.stepsize", 3*1000)
  if (Sys.getenv("CI")) {
    time <- time * 2
  }
  time
}
```

**Comment by wch** [comment]
Another:

```R
app <- AppDriver$new(timeout_stepsize = 3*1000, timeout = self$get_timeout(10))

app$get_js(timeout = self$get_timeout(1))

app$get_timeout(steps = 1)

app$set_timeout(stepsize = 3 * 1000)
```
