### ISSUE TITLE
Url R6Class set method builds and sets an incorrect URL when query parameters with no value are passed

### ISSUE THREAD

**Issue by zsigmas** [rstudio/shinytest2#222]
### Code to reproduce:
```
url <- shinytest2::Url$new()
url$set("http://127.0.0.1:1234/?_inputs_&n=10")
url$get()
# Returned value: [1] "http://127.0.0.1:1234/?_inputs_=&n=10"
# Expected value: [1] "http://127.0.0.1:1234/?_inputs_&n=10"
# Notice the '=' after '_inputs_' in the returned value
```

### Origin:
The origin of the bug can be pinpointed to:
https://github.com/rstudio/shinytest2/blob/29c7a6b2cfc83de720acc5ca86cdab73dca7ad0e/R/R6-helper.R#L60

This function receives the following value in `res`:
```
$scheme
[1] "http"

$hostname
[1] "127.0.0.1"

$port
[1] "1234"

$path
[1] ""

$query
$query$`_inputs_`
[1] ""

$query$n
[1] "10"


$params
NULL

$fragment
NULL

$username
NULL

$password
NULL

attr(,"class")
[1] "url"
```
It treats `_inputs_` as a query parameter (in fact it is one but it has a special meaning in shiny) and tries to reconstructs it as such.

### Possible approaches for solutions

I am unsure if the behavior of `httr::build_url` is the expected one as it does not return `_inputs_=""`, but only `_inputs_=`. There are no particular specifications for this case in the reference doc in https://httr.r-lib.org/reference/parse_url.html

Fixing it locally would imply treating `_inputs_` query parameter as a special case. Unsure of the best approach as introducing `_inputs_` may not be trivial as it may not may be in some cases placed immediately after '/?'. And grepping and replacing can be dangerous as it could match things like `http::127.0.0.1:1234/?_inputs_&conflicting_input='_inputs_='`.

### Relevance
This will very likely have a direct impact in the enhancement proposed in #219

**Comment by schloerke** [comment]
Hmmmm. When I run with the latest version `httr`, I get:

```r
u <- Url$new()
u$set("http://127.0.0.1:1234/?_inputs_=&barret&n=10")
u$get()
#> [1] "http://127.0.0.1:1234/?_inputs_=&barret=&n=10"
```

Maybe I'll bump the required httr version

**Comment by schloerke** [comment]
Addressed in https://github.com/rstudio/shiny/pull/3648
