### ISSUE TITLE
error using the record_test/test_app

### ISSUE THREAD

**Issue by mehrnoushmalek** [rstudio/shinytest2#227]
Hi, 
I was getting a weird error when testing and couldn't figure out why. At first I thought my Rstudio doesn't support it, but I decided to run the codes line by line, and realized that the ","  in line 348 of the _app.R_ in **inst/internal/recorder** was the one that caused the error for me.
Now I'm gladly seeing the browser, and can do the test, but when saving, I get the error of `cli::style_hyperlink(paste0(basename(filename), ":", x$srcref[1],  : unused argument (params = c(line = x$srcref[1], col = x$srcref[2]))`
which is used in **testthat**. I updated both **testthat** and **cli** packages, but it's still the same. Do you happen to know what I can do?

Thanks a lot!

**Comment by schloerke** [comment]
There's been issues with `{cli}`. I hope that has resolved some of it. 

I'm going to fix the trailing comma in `app.R` in #239 . If this does not resolve your `cli::style_hyperlink(paste0(basename(filename), ":", x$srcref[1], : unused argument (params = c(line = x$srcref[1], col = x$srcref[2]))`, can you record a video or provide a full reprex of what is happening and open a new issue? 

Thank you!
