### ISSUE TITLE
Allow expect_download to test download success without comparing files

### ISSUE THREAD

**Issue by rbcavanaugh** [rstudio/shinytest2#233]
I would like to write a test simply to verify that a file was successfully downloaded. However, if the file is a .pdf generated from an rmarkdown report, then the expect_download function always fails: I don't actually need to check whether the content is correct (I can just test the values of the parameters fed to the rmarkdown template). But I would like to check that the file rendered. 

A way that it seems like I can do this is by testing that the file length is expected (here, 33 characters long). 
`testthat::expect_equal(length(app$expect_download("downloadReport")), 33)`

However, the test will always fail the expect_download test because its trying to compare the 002.download file. Is there a way to ignore the file comparison and just check that the file name is correct or has the correct length?

thanks! Error below:

```
Warning: Error in rawToChar: embedded nul in string: '%PDF-1.5\n%\xd0\xd4\xc5\xd8\n8 0 obj\n<<\n/Length 1390      \n/Filter /FlateDecode\n>>\nstream\nxڵX\xdbn\xdb8\020}\xf7W\xe8%X\t\x88\xb9\xbc\x88\xa2Էl\x9a\026)\xb6\xdb.ⷶX(\x91\xec\b\xab\xdbZVR\xff})r\xa8\x9bi\xe7\xd2.\020\xd8&\xa5\031\xce\xcc9gH\006;\033\a;\xef\027\xf8\x89\xef?V\x8b\xdf߅\xdc!\002Q\xc2}g\xb5v\b\026H\xb0\xc8\t\x82\020\x91HN%\xce\027wu\x9fzK\x8a\xb1{Q\xdf\xc7M\026\xeb\xc1eU\024m\x99\xddy\004\xbb\xb1G|w\x97U\xa5~\xf4\xa9\xddu\023w\036%nU\x80\xf1Ǵ\x9b\x8b\x9bv\xdbY\xc0\xe4W\xcc\xf1E7\xbe\xf4h\xe4~\xfa(\xc7\xc4\xfb\xb6\xfa \xe3\n\x9d\bE\001\r\xba\xb0\x96\x8c\xab\xb0\x96\xbe@!\xd5QݴE\021o\xbd%w\xf7`\xc1\xc7\026\030\xd1@\032\x90H\xe6\026\x9a<\xb2F/\x9b\x95I\xf6\x90%m\x9c\xff\xe6\xf9\x91\v\xb3+O0w\xd9\xe8\xb0\xc7Q\xa6\x8dG\xb1̯\xd0yv\037\xf0\xa4Z\xebo.\020\021CJ\021?\xd3\003\xed\xab\xfc\x8a\x99\x9f\xa4\xa5\032\xa5&\004\xedGf@\xb9\xfb\xd0-\020\xe7o\xe4\x801\x973\024E\xe7\xfa\xbd\0#\xc6UY\xfa\xc8G%W. \xfc&\xcd\xd7\xddx\xa9C\xaf\ [... truncated]
  103: rawToChar
  102: raw_to_utf8
  101: file_data
  100: diffviewer::visual_diff
   99: ::
htmlwidgets
shinyRenderWidget
   98: func
   85: renderFunc
   84: output$diff
    3: shiny::runApp
    2: review_app
    1: testthat::snapshot_review
Accepting snapshot: 'tests/testthat/_snaps/acom-38-mostly/002.download'
```

**Comment by schloerke** [comment]
Allowing for `compare = FALSE` but still performing a snapshot on the download name seems too custom for now.  

With the ability to call `$get_download()` and gather information from there, I'm going to close this issue.

**Comment by rbcavanaugh** [comment]
Fantastic - thanks for the workaround. This exactly what I'm looking for - no need for a custom `compare = FALSE`. Much appreciated!
