### ISSUE TITLE
Github action cannot resolve rstudio/shinytest2@v1

### ISSUE THREAD

**Issue by paulimer** [rstudio/shinytest2#246]
Hi,
I followed the guide [Using shinytest2 with continuous integration](https://rstudio.github.io/shinytest2/articles/use-ci.html), but there seems to be an issue with the action `rstudio/shinytest2/actions/test_app@v1`, as Github throws the error : `Error: Unable to resolve action rstudio/shinytest2@v1, unable to find version v1`. 
Is there an issue with this, or have I failed to follow the guide (very possible)?
Looking around Github for an anwser, I find the command failing at the same step elsewhere, such as [here](https://github.com/nate-d-olson/learn_shinytest2/runs/7528654547?check_suite_focus=true)

**Comment by schloerke** [comment]
🤦‍♂️ My fault. Forgot to tag it when I released.

**fixing

------------

At any time if you'd like the bleeding edge, you can use: `rstudio/shinytest2/actions/test_app@main`

**Comment by schloerke** [comment]
Tag: https://github.com/rstudio/shinytest2/releases/tag/v1

**Comment by schloerke** [comment]
Thank you, @paulimer !

**Comment by paulimer** [comment]
That was quick, thanks a lot!

**Comment by paulimer** [comment]
I actually land at another error: `Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/_actions/rstudio/shinytest2/v1/actions/test_app'. Did you forget to run actions/checkout before running your local action?`, is it something to do with me this time?

**Comment by schloerke** [comment]
Docs are inconsistent 🤦‍♂️ 

Can you use `test-app` instead of `test_app` in your step location?

Thank you for your follow up! I'll adjust the docs later today

**Comment by paulimer** [comment]
That was it! Thank you

**Comment by schloerke** [comment]
(Will keep open until docs are fixed)
