### ISSUE TITLE
Can the C key sort order be changed?

### ISSUE THREAD

**Issue by bersbersbers** [rstudio/shinytest2#254]
I thought that I had tackled https://github.com/rstudio/shinytest/issues/409 for good after fixing `LC_COLLATE` and switching to `shinytest2`, but it seemed to have made a comeback of sorts over the summer. What I now observe is that my previously passing tests fail due to JSON key ordering, and it seems to have something to do with `shiny` 1.7.2 (1.7.1 still works). In line with that, `shiny`s changelog says
> When taking a test snapshot, the sort order of the json keys of the input, output, and export fields is currently sorted using the locale of the machine. This can lead to inconsistent test snapshot results. To opt-in to a consistent ordering of snapshot fields with {shinytest}, please set the global option options(shiny.snapshotsortc = TRUE). **{shinytest2} users do not need to set this value.** (#3515)

This is somewhat of a breaking change for `shinytest2` users. Is there an easy way of reverting this, or is this hard-coded? I tried setting `options(shiny.snapshotsortc = TRUE)`, but without effect - it may be that `shinytest2` is overriding it in line 279:

https://github.com/rstudio/shinytest2/blob/08c4060609d5ee9b52278521a08cbf4e0593ffb4/R/app-driver-expect-values.R#L273-L281

Compare also 
>           # {shinytest2} will always set `sortC=1`

https://github.com/rstudio/shiny/blob/04ad1453c1e511670275efeb5325caf0b65e133c/R/shiny.R#L494

I could live with C sort order, but before I go through all failed tests one be one, is there an easy way to opt out of C sort order?

**Comment by schloerke** [comment]
`sortC=1` support was added in `{shiny}` 1.7.2.  

> This is somewhat of a breaking change for `{shinytest2}` users.

Yes. Sorry. We only believed it would be a handful of users who would get bit by the change.

`{shinytest2}` does not have a way to opt out of C sort order.  `{shiny}` added support for in rstudio/shiny#3515 
 and `{shinytest2}` has always attempted to sort using C sort order (hard-coded) given rstudio/shiny#3515.

**Comment by bersbersbers** [comment]
Understood, thanks for the answer. I was able to (relatively) quickly, heuristically confirm the equivalence of pre- and post-change JSON files by `textconv` approach in `git`, using `sort` as the "text converter" - meaning I accepted all changes und then confirmed that `git diff` does not report relevant changes in the JSON files.

**Comment by bersbersbers** [comment]
> Yes. Sorry. We only believed it would be a handful of users who would get bit by the change.

Oh, and no worries: I consider `shinytest2` pre-release software, so I am fine with breaking changes (even if this change was in `shiny`, technically).
