### ISSUE TITLE
Snapshot directory message is misdirected

### ISSUE THREAD

**Issue by russHyde** [rstudio/shinytest2#272]
Hi.
I have a package that creates an app identical to the following

```
ui <- fluidPage(
    textInput("name", "What is your name?"),
    actionButton("greet", "Greet"),
    textOutput("greeting")
  )
server <- function(input, output, session){
  output$greeting <- renderText({
    req(input$greet)
    paste0("Hello ", isolate(input$name), "!")
  })
}
```

I noticed that the test snapshots are getting saved to a different location from where the testthat messages indicate:

A simple test is as follows:

```r
# ./tests/testthat/test-e2e-greeter_accepts_username.R
test_that("the greeter app updates user's name on clicking the button", {
  username = "Me"

  # Start the app
  shiny_app = run() # this is the function to create the running-app object
  app = shinytest2::AppDriver$new(shiny_app, name = "greeter")

  # Describe the test setup and actions
  app$set_inputs(name = username)
  app$click("greet")

  # Make your assertions
  values = app$expect_values(output = "greeting", screenshot_args = FALSE)
})
```

That works fine. The snapshot gets saved to `./tests/testthat/_snaps/e2e-greeter_accepts_username/greeter-001.json`

But on running the test for the first time the I get the following message:

```
Warning (test-e2e-greeter_accepts_username.R:29:3): the greeter app updates user's name on clicking the button
Adding new file snapshot: 'tests/testhat/_snaps/greeter-001.json'
```

Apologies for the lengthy set-up:

With test-script `./tests/testthat/test-<script-infix>.R`,

- Snapshot location is `./tests/testthat/_snaps/<script-infix>/<app-driver-name>-001.json`
- testthat message is "... new file snapshot `./tests/testthat/_snaps/<app-driver-name>-001.json`"

**Comment by schloerke** [comment]
Great reprex! I appreciate all the info. Thank you!

[This is bug](https://github.com/r-lib/testthat/pull/1610/files#diff-b160fbd7e71f641d2023365127f1348d682a0f17db8290443938255d7d3dfae5R192) within `{testthat}`. Good news, it has been fixed an in testthat v3.1.4.

Please update to the latest `{testthat}` and let me know if it still exists.
