### ISSUE TITLE
shinytest2 can't find package in Github Actions

### ISSUE THREAD

**Issue by alexquant1993** [rstudio/shinytest2#273]
Hi Barret,

I am developing a Shiny app and I am currently using the shinytest2 framework to test my app reactivity with googlesheets and gmail.  Here are some details of my app and issue:

1. URL: https://github.com/alexquant1993/shareIBC
2. Golem framework.
3. Issue: CI issues using Github Actions for the test-coverage workflow. When I execute the tests and test coverage locally, everything works perfect. Nevertheless, once I try to run the same tests within any CI workflow, the tests break. It seems that the AppDriver object is correctly initiated, but the AppDriver$set_inputs() function does not work. As you can see, all inputs are not correctly updated by set_inputs() and are left as NULL.
![image](https://user-images.githubusercontent.com/57950268/193680855-2c1b0031-8c7e-4d02-bcdb-ee1fa3f59c65.png)
5. All tests run smoothly but the ones related to shinytest2.

I do not know what I am doing wrong, specially when @StatisMike is using more or less the same testing framework and he does not seem to have problems with his test-coverage workflow.
https://github.com/StatisMike/shiny.reglog

**Comment by alexquant1993** [comment]
Hi Barret,

Thank you very much for your detailed answer. Here are the steps I've followed to get the test coverage workflow working:

1. I updated my [Github Actions workflow](https://github.com/alexquant1993/shareIBC/blob/master/.github/workflows/test-coverage.yaml) to install my package and make it available for shinytest2 . Also, now I'm working with {renv}. I wanted to make sure that the tests weren't breaking due to the package versioning within the CI setup.
2. Updated my tests to not test JavaScript functions, eg emptying input fields. Initially the tests will work locally but not in Github Actions. Here is the type of error I was getting: 
![image](https://user-images.githubusercontent.com/57950268/194779957-32edaec6-d9ff-4f48-b41f-eecdbf1e1eab.png)
3. Regarding your last comment "Even if we fix everything, unfortunately the test coverage when executed with {shinytest2} is not reported to {covr}". I was able to successfully upload my [test coverage report](https://github.com/alexquant1993/shareIBC/actions/runs/3215535093/jobs/5256699795#step:8:43). However, I get really different results locally and in CI:
![image](https://user-images.githubusercontent.com/57950268/194780246-473903cf-769e-4dcf-a60f-039c9efec154.png)
![image](https://user-images.githubusercontent.com/57950268/194780271-b1a282e1-0646-4a6d-b193-bf86e68b15f5.png)

Best regards,

Anderson

**Comment by schloerke** [comment]
Thank you for the followup!

> I was able to successfully upload my [test coverage report](https://github.com/alexquant1993/shareIBC/actions/runs/3215535093/jobs/5256699795#step:8:43).

That's awesome! I don't know how that's possible... 🤔  . I'd expect minimal coverage as your local screenshot shows.



-----------------

Closing as issue seems resolved
