### ISSUE TITLE
Apps with file name other than `app.R`

### ISSUE THREAD

**Issue by asbates** [rstudio/shinytest2#285]
This is part feature request, part question. The feature request may be moot depending on the answer to the question.

Feature:

I would like to be able to test applications in files with names other than `app.R` (or `server.R`/`ui.R` pair). For example, say `tests/testthat/apps` directory contains `app1.R`, `app2.R`, etc. I'd like to do this because having each app in it's own directory, and every app directory having `tests` and `tests/testthat` feels a bit extra.

Question:

The above leads me to the question, is there a reason why `shinytest2` requires each tested app to be in it's own directory with an associated `app.R`? I see `shinytest2` has `tests/testthat/apps` with subdirectories for each app to be tested. So I'm wondering if that's a style preference or if there's some sort of technical reason.

**Comment by schloerke** [comment]
Sorry about the premature closing of the Issue. Hit the wrong button.

-----------------------

> Question:
> 
> The above leads me to the question, is there a reason why `shinytest2` requires each tested app to be in it's own directory with an associated `app.R`? I see `shinytest2` has `tests/testthat/apps` with subdirectories for each app to be tested. So I'm wondering if that's a style preference or if there's some sort of technical reason.

When running apps from a directory it can be cluttered very quickly. It felt _wrong_ for me to encourage users to write multiple `app.R` files to have the ability to share `global.R` file and `./R` folder.  Snapshot files would not be consistent when using different apps, so it would cause snapshots to be inconsistently produced. 

By requesting a directory, only a single file can be started. Therefore only the tests and snaps related to that single app are run. 

-----------------------------------------------------

However, I believe there is a solution to your feature request. `AppDriver$new(app_dir=)` can take anything that [returns `TRUE` for `shiny::is.shiny.appobj(app_dir)`](https://github.com/rstudio/shinytest2/blob/ed38d82de7ac8dd7504cde119a6f3ec74868d1f4/R/app-driver-initialize.R#L55-L57). So if you have a function (or code) that can make an app object or even define your app in your test file, you can supply that directly to `AppDriver$new(app_dir=)`.

Examples: 
* Write the app in the test: https://github.com/rstudio/shinytest2/blob/ed38d82de7ac8dd7504cde119a6f3ec74868d1f4/tests/testthat/test-save-app.R#L5-L16
```r
n <- 5
shiny_app <- shinyApp(
  ui = fluidPage(textOutput("text")),
  server = function(input, output) {
    output$text <- renderText(n)
  }
)
app <- AppDriver$new(shiny_app)
```
* Make the app object directly:
```r
shiny_app <- shiny::shinyAppDir(system.file("examples/01_hello", package = "shiny"))
app <- shinytest2::AppDriver$new(shiny_app)
```


When using either of these approaches, you can have many shiny apps within the same testing file (Ex: https://github.com/rstudio/shinytest2/blob/ed38d82de7ac8dd7504cde119a6f3ec74868d1f4/tests/testthat/test-save-app.R).

**Comment by asbates** [comment]
Got it. Thanks for the clarification!
