### ISSUE TITLE
`$expect_screenshot()` isn't compatible with rlang splicing (`!!!`)

### ISSUE THREAD

**Issue by cpsievert** [rstudio/shinytest2#292]
See for example https://github.com/rstudio/shinycoreci/blob/b4e06bf1/inst/apps/304-bslib-card/tests/testthat/test-shinytest2.R#L33-L34

**Comment by schloerke** [comment]
I don't know if it should.

Maybe should be `rlang::inject(app$expect_screenshot(!!!args)` or `rlang::exec(app$expect_screenshot, !!!args)` in rstudio/shinycoreci.

**Comment by schloerke** [comment]
Closing as I don't believe `!!!` support should be added here
