### ISSUE TITLE
How to use a variable inside a shiny app?

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest2#303]
I'm trying to create a unit test where I set a variable at the start of the {testthat} unit test and use that variable in a shiny app, then use {shinytest2} to test the app. However, it seems like I can't refer to that variable when wrapping my app in an AppDriver.

Example:

```r
foo <- 5

app <- shiny::shinyApp(
  ui <- shiny::fluidPage(),
  server = function(input, output, session) {
    foo
  }
)

driver <- shinytest2::AppDriver$new(app)
driver$get_logs()
```

You'll see the error message `object 'foo' not found`

**Comment by schloerke** [comment]
I can duplicate the error if run in the R console. 

The error goes away if run within a testthat file.

Are you running your code in the R console?

---------------------

I can get this to work as expected in the R console:

```r
app <- local({
  foo <- 5
  foo3 <- 19

  shiny::shinyApp(
    ui <- shiny::fluidPage(textOutput("foo")),
    server = function(input, output, session) {
      foo3
      foo2 <- foo + 1
      output$foo <- renderText({
        foo2
      })
    }
  )
})

driver <- AppDriver$new(app)
driver$get_logs()
```

If `foo3` is outside of `local()` and run in the R console, it will fail.

Fails:
```r
foo <- 5
app <- local({

  foo3 <- 19

  shiny::shinyApp(
    ui <- shiny::fluidPage(textOutput("foo")),
    server = function(input, output, session) {
      foo3
      foo2 <- foo + 1
      output$foo <- renderText({
        foo2
      })
    }
  )
})

driver <- AppDriver$new(app)
driver$get_logs()
```

**Comment by schloerke** [comment]
I believe I've found a fix. Will make a PR tomorrow.
