### ISSUE TITLE
Using glue inside driver$wait_for_js() causes error in GitHub Actions

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest2#316]
Using `glue::glue()` inside a `wait_for_js()` passes locally, but consistenly fails on GitHub Actions with the following obscure error:

```
Error in `chromote_wait_for_condition(self$get_chromote_session(), script, 
    timeout = timeout, interval = interval)`: Error found while waiting for JavaScript script to return `true`.
i `script`:
true
i Error:
SyntaxError: Unexpected token '='
```

This nasty one took me my entire Sunday to figure out because the error message makes no sense, at least not to me 🤷‍♂️ 

To reproduce, I create a sample repository https://github.com/daattali/shinytest2test

It shows that `driver$wait_for_js("true")` works, `driver$wait_for_js(as.character(glue::glue("true")))` works, but `driver$wait_for_js(glue::glue("true"))` errors

It's possible that this issue is with a different package that shinytest2 is using, so feel free to transfer to a different repo (please tag me if you do because GitHub doesn't notify me and then I lose a reference to this issue and won't know when it's fixed)

**Comment by daattali** [comment]
By the way, `driver$get_js()` doesn't have an issue with glue.

**Comment by schloerke** [comment]
https://github.com/rstudio/shinytest2/pull/288 has been merged into `main` branch. 

Does this fix it?

**Comment by daattali** [comment]
How would I test that on GHA? If shinytest2 is currently in the "Suggests" field of the DESCRIPTION, do I need to add it to "Remotes:" so that the latest version will be used by GHA?

**Comment by schloerke** [comment]
Correct. It must be in the `Remotes` section of the DESCRIPTION file

**Comment by daattali** [comment]
That fixed it!
