### ISSUE TITLE
Testing multiple applications fails package check

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest2#318]
When implementing the recommended method of testing multiple applications, the package check fails at the end of testing even though the tests pass (running `devtools::test()` or clicking the Test button in RStudio works, but `devtools::check()` or the Check button result in this error)

```
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 29 ]
Error in data.frame(file = test$file, context = context, test = test$test,  : 
  arguments imply differing number of rows: 1, 0
Calls: test_check ... as.data.frame.testthat_results -> lapply -> FUN -> data.frame
Execution halted
```

After some troubleshooting, it seems that this happens only when I use the method of placing each app in its own folder with the entire tests/testthat/setup directory structure. I haven't created an isolated reprex, but I did reproduce it in my existing package:

- [In commit 1](https://github.com/daattali/shinyjs/commit/6f7ad098f74c1f085a243b3c71013ca149b4021d#diff-85fef44534d914754d5a6e23ccbc9677cec5fc79d9da61b12be2cfba9b261f5e), I removed the shinytest2 testing and this passed GHA checks 
- [In commit 2](https://github.com/daattali/shinyjs/commit/51419dfcf1c0cee4709ce5940c221ab4e6e8e438) I re-introduced the shinytest2 testing using the method of testing each app directory. There was only one app directory and it was an extremely simple app https://github.com/daattali/shinyjs/blob/51419dfcf1c0cee4709ce5940c221ab4e6e8e438/tests/testthat/apps/test/app.R . This caused the GHA error seen above even though the tests do pass.
- [In commit 3](https://github.com/daattali/shinyjs/commit/9a9838e2f71fa898a616e432c91b5d895b43b866) I moved away from testing per app directory and instead I placed the entire app code inside the test script, and this works

**Comment by schloerke** [comment]
This seems like a testthat issue as `as.data.frame.testthat_results()` is inside `{testthat}`. 

We'll keep the issue here until we can get closer to the bug

**Comment by daattali** [comment]
Maybe the issue should be moved to testthat repo then?

**Comment by schloerke** [comment]
> Maybe the issue should be moved to testthat repo then?

Until we have a reprex, I'd like to keep it here.

-----------------------

Does adding a test to the file help? Currently there are no tests in the file and the error had `  arguments imply differing number of rows: 1, 0`.

Wondering if we add the test (below) to the file, then a "test" is recorded.

```r
test_that("multiplication works", {
  expect_equal(2 * 2, 4)
})
```

**Comment by daattali** [comment]
If you meant adding that to the file that recursively calls `test_app()` on all the apps, then that did not seem to fix the issue. The file is now 

```r
testthat::skip_on_cran()

library(shinytest2)

lapply(list.files("apps", full.names = TRUE), function(folder) {
  shinytest2::test_app(folder)
})


test_that("multiplication works", {
  expect_equal(2 * 2, 4)
})
```

And I still get the same error

**Comment by daattali** [comment]
I've created a reprex. 

https://github.com/daattali/shinytest2bug318

You can use that to determine what repo the bug report belongs in (and hopefully to find a fix!)

**Comment by schloerke** [comment]
So this `{testthat}` bug was surfaced in due to `{shinytest2}` doing odd things.

I believe we should just accept this bug exists until #308 is implemented. Then it should disappear given we are nesting our executions of `testthat::test_dir()`.

-------------------------------

Workaround: Add a test before and after your calls to `test_app()`.

Ex from your reprex repo:
```r
# ./tests/testthat/test-apps.R
test_that("addition works", {
  expect_equal(1 + 1, 2)
})

lapply(list.files("apps", full.names = TRUE), function(folder) {
  shinytest2::test_app(folder)
})

test_that("addition works again", {
  expect_equal(1 + 1, 2)
})
```

**Comment by schloerke** [comment]
Going to close this issue as there is a work around and plans for a different approach down the road.
