### ISSUE TITLE
test-app action's app-dir parameter doesn't work well with renv

### ISSUE THREAD

**Issue by cpsievert** [rstudio/shinytest2#323]
`app-dir` should be passed directly to the `test_app()` call or else the (recommended) renv-in-the-root-folder setup won't work

https://github.com/rstudio/shinytest2/blob/96a1d282afcc3139f98d73a16d8e08c814f94948/actions/test-app/action.yml#L24-L30

**Comment by schloerke** [comment]
Fair. Thank you!
