### ISSUE TITLE
error with shinytest2::AppDriver$new

### ISSUE THREAD

**Issue by NikolozAz** [rstudio/shinytest2#352]
Hello shiny devs,

i am trying to get started with the shinytest2 package and encounter an errror already when running shinytest2::record_test or shinytest2::AppDriver$new(getwd()). I tried to run those codes also with the simple shiny app from your getting started with shinytest2 webpage (https://rstudio.github.io/shinytest2/articles/shinytest2.html). This error looks as follows.
![shinytest2_error](https://github.com/rstudio/shinytest2/assets/61994351/5044e30f-a1e6-4160-9756-81ce7c1a6996)
As a remark i wanted to add, that when i run for example shinytest2::record_test all my opened chrome pages are reloaded.
Has anyone the same issue? Thank you in advance!

**Comment by schloerke** [comment]
Yes, the failure is not related to shinytest2. (But, we can finish our conversation here.)

I don't understand why your machine can not open a port. Are you able to successfully run this code?

```R
 httpuv::randomPort()
```

**Comment by NikoloBlunder** [comment]
Okay, thanks. I was able to run that code successfully. It returns 9899 as a value.

**Comment by schloerke** [comment]
Hmmmmm.  I don't know then. Maybe updating your Google Chrome installation will fix it?

Once you're able to successfully run `chromote:::launch_chrome()`, then then the original `{shinytest2}` problem should be fixed.

**Comment by NikoloBlunder** [comment]
Okay, thank you. I will try it.

**Comment by NikoloBlunder** [comment]
It turns out that as that function of chromote package (chromote:::launch_chrome()) is internal function, the security system of a company doesn't allow it to run. So for now, i won't be able to use it. But nice to know it and thank you for your help!
