### ISSUE TITLE
Request: more docs on example-test-app-description.yaml

### ISSUE THREAD

**Issue by nick-youngblut** [rstudio/shinytest2#358]
The docs at https://rstudio.github.io/shinytest2/articles/use-ci.html show the [example-test-app-description.yaml](https://github.com/rstudio/shinytest2/blob/main/actions/test-app/example-test-app-description.yaml) GitHub Actions example. 

It's not clear why the `GITHUB_PAT` env variable must be provided. A bit more documentation on this aspect of the example (and maybe other aspects such as the (dis)advantages of `R_KEEP_PKG_SOURCE`) would be helpful.

**Comment by nick-youngblut** [comment]
Thanks @gadenbuie for providing all of the information! 
Feel free to close this issue, if you have updated the docs or just want this info to live in this issue.

**Comment by gadenbuie** [comment]
@nick-youngblut You're welcome, I appreciate the question! It feels a bit in the weeds for the docs, though, so I'm happy that we now have this issue as a way to document the answer for those who are curious.
