### ISSUE TITLE
seed parameter not fixing renderUI's auto-generated div IDs

### ISSUE THREAD

**Issue by alex-silverman** [rstudio/shinytest2#363]
tests keep failing shinytest2's comparisons because of renderUI()'s auto-generated div ids, e.g. out63cdc91c431ff1ea. I thought setting the driver's seed would fix the problem but the IDs keep changing.

A more detailed explanation of the issue is here: https://stackoverflow.com/questions/77298716/shinytest2-json-comparisons-fail-because-of-renderui-div-ids

Here's a pared-down version of the test script:

```r
library(shinytest2)
test_that("{shinytest2} recording: test-good", {
    print("Running test-good")
    app <- AppDriver$new(
        variant = platform_variant(), 
        name = "test-good", 
        seed = 1234,
        load_timeout = 1e+05)

app$set_inputs(sidebarmenuid = "tabClientCount")
app$wait_for_idle(500) #wait until whole application is idle for 500ms
app$expect_values()
})
```

**Comment by schloerke** [comment]
@alex-silverman 
> because of `renderUI()`'s auto-generated div ids

Can you add a reprex app that shows this behavior? It will help me debug the random ids. 

Thank you!

**Comment by alex-silverman** [comment]
You were, of course, right to ask me to do a reprex. It led me to discover the source of the problem: **nested renderUIs**. I'm not sure *why* that results in the ID changing, but with the nesting it fails, and without the nesting it passes. Do you know why that would be?

**Comment by schloerke** [comment]
> It led me to discover the source of the problem: **nested `renderUI()`s**. I'm not sure *why* that results in the ID changing, but with the nesting it fails, and without the nesting it passes. Do you know why that would be?

No. Every `renderUI()` call has a corresponding `output$ID_VALUE`.

Can you add your paired down Shiny app to show off this behavior? It is odd as it really does seem like it happening on the R side, so I don't know why the random ID is being generated for the UI output.

If it is a bug, I would like to add the app in shinytest2's test suite.

**Comment by alex-silverman** [comment]
Just tried attaching the zip. This includes two outputs, a "bad" (ever-changing ID due to nested `renderUI()`s) and a "good" (static, with just one `renderUI()`). It also includes the test stuff, including the results.
[eva-reprex.zip](https://github.com/rstudio/shinytest2/files/12917415/eva-reprex.zip)

**Comment by schloerke** [comment]
Thank you for the app code!  The inner `renderUI` was not being stored to `output`. I could not easily find where the id value was being set. 

However...

-------------------------

You have a `anti-solution` in your app. Joe Cheng talks about this here: https://posit.co/resources/videos/reactivity-pt-1-joe-cheng/ 

Rule to follow: Do not nest reactive expressions inside other reactive expressions.
Ex: 
* Do not put a renderUI inside of a renderUI's expression.
* Do not put a renderUI inside of another `observe()`'s expression
* Do not put a `reactive()` function inside a render method or `observe()` expression.
* Do not assign to `output` inside a reactive expression.

Exception:
* You are inserting new, dynamic data for the first time and need to create new reactive expressions. (Such as `insertUI()`, adding a new tab to the UI, etc.). 

This exception is pretty rare. Most reactivity can be resolved without an anti-solution.

---------------------------------

#### Current app code

(with `header_good` code removed)

```r
library(shinydashboard)
library(shiny)

ui <- fluidPage(
  htmlOutput("header_bad")
)

server <- function(input, output, session) {
  output$header_bad <- renderUI({
    renderUI({
      h4("Div with Ever-Changing ID")
    })
  })
}

shinyApp(ui, server)
```

The "current app" code called a `renderUI()` inside another `renderUI()`'s reactive expression. This breaks the rule above, creating an anti-solution.


#### Proposed app code

```r
library(shinydashboard)
library(shiny)

ui <- fluidPage(
  # The outer UI output will return an inner UI output
  htmlOutput("header_outer")
)

server <- function(input, output, session) {
  output$header_outer <- renderUI({
    # Return a UI component. This will cause `output$header_inner` to attempt to render after shiny becomes idle
    htmlOutput("header_inner")
  })
  # Will wait until `htmlOutput("header_inner")` exists in the browser before rendering
  output$header_inner <- renderUI({
    h4("Inner Div with Static ID")
  })
}

shinyApp(ui, server)
```

This app moves the "inner" renderUI outside of the previous renderUI's expression. It is ok to have (what seems like) inactive reactive expressions that are waiting until the requested output value needs to be processed. 

----------------

So I don't know where the ID value is being set. To me, the app seems to be accidentally working. If you absolutely need to keep the inner render call inside the outer render, be sure to store it into `output` to connect the reactivity.

**Comment by alex-silverman** [comment]
I see. So you're saying I SHOULD be attaching all renderUIs to outputs (which have IDs), but if I don't Shiny is smart enough to generate a random ID for me. I do think this was not a problem with `shinytest`, but I see why it's "correct" to attach it to an output.

I'll think about how to incorporate a fix. I can close the issue if you'd like.

**Comment by schloerke** [comment]
> So you're saying I SHOULD be attaching all renderUIs to outputs

Correct!

> but, if I don't, Shiny is smart enough to generate a random ID for me

I honestly don't know where this logic is 😅 ... But we should avoid anti-solutions and always assign the render function result to `output`.


-----------------

Closing issue.

Please add a comment if you do / don't find a solution. Thank you!
