### ISSUE TITLE
Remove internet dependencies.

### ISSUE THREAD

**Issue by jarodweber** [rstudio/shinytest2#383]
When using wait_for_value() the function ends up calling app_httr_get() with in this function it calls pngr::is_up(). In the pngr documentation it states the check_online paramter for is_up() is defaulted to TRUE. This causes the user interface tests with wait_for_value() to fail with no internet connection and causes inconsistencies when running the tests due to internet speeds. Setting check_online = FALSE in this function would reduce false positives in the testing and also reduce the runtime of the testing suite.

**Comment by schloerke** [comment]
Fixed in #364
