### ISSUE TITLE
`app$click("inputId")` does not work with a `bslib::input_task_button`

### ISSUE THREAD

**Issue by stla** [rstudio/shinytest2#388]
Hello,

Please take a look at <https://stackoverflow.com/q/78517385/1100107>.

To sum up, we have a `bslib` button `input_task_button("run_async", "Run async")`, and with **shinytest2** we do 

```r
app <- AppDriver$new(shiny_app)
app$click("run_async")
```

Then that does not work.

An alternative which works is `app$click(selector = "#run_async")`.

Cheers.

**Comment by schloerke** [comment]
Thank you! Should be fixed in #389 

Thank you for the work around on SO.
